### ISSUE TITLE
Wrong Paste Name

### ISSUE THREAD

**Issue by rafescu** [iptomar/projectary-docs#9]
It's Análise de Sistemas and not Ánalise de Sistemas

Slides/Análise de Sistemas

**Comment by asantos3** [comment]
Shouldn't be any of those two, we shouldn't use diacritical marks on folders or files.

**Comment by rafescu** [comment]
Maybe Slides/AS is better

**Comment by asantos3** [comment]
Uhm, just changed to 'Analise de Sistemas' at https://github.com/iptomar/projectary-docs/commit/eb47564f459aa5cdeb66566c0cec6d52b20ca12e
